# Generated by Django 4.0.1 on 2022-01-27 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_age_guitar_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('string', models.CharField(choices=[('X', 'Extra Lite'), ('L', 'Lite'), ('M', 'Medium')], default='X', max_length=1)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.guitar')),
            ],
        ),
    ]
